name: Set up repository
description: Set up a yarn repository and install package.json


runs:
  using: 'composite'
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn --frozen-lockfile
      shell: bash
